services:
  #Payara server
  payara:
    container_name: payara-RealEstateHub
    image: payara/server-full:6.2025.8-jdk17
    environment:
      SECURE_ADMIN: "true"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin"
    ports:
      - "8080:8080"   #apps
      - "4848:4848"   #admin console
    volumes:
      #auto deploy (maps local target artefact to container)
      - ./WebService_RealsEstateHub/target/WebService_RealsEstateHub-1.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/WebService_RealsEstateHub-1.0-SNAPSHOT.war
      - ./WebApplication/target/WebApplication-1.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/WebApplication-1.0-SNAPSHOT.war

